/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ActionEnum = {

    /**
     * TODO: Write general description for this element
     */
    INCREASE: 'increase',

    /**
     * TODO: Write general description for this element
     */
    DECREASE: 'decrease',

};

module.exports = ActionEnum;
