/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AggregatedByEnum = {

    /**
     * TODO: Write general description for this element
     */
    DAY: 'day',

    /**
     * TODO: Write general description for this element
     */
    WEEK: 'week',

    /**
     * TODO: Write general description for this element
     */
    MONTH: 'month',

};

module.exports = AggregatedByEnum;
