/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Createsubaccount
 */
class Createsubaccount extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.username = this.constructor.getValue(obj.username);
        this.email = this.constructor.getValue(obj.email);
        this.setpassword = this.constructor.getValue(obj.setpassword);
        this.password = this.constructor.getValue(obj.password);
        this.creditType = this.constructor.getValue(obj.creditType || obj.credit_type);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'username', realName: 'username' },
            { name: 'email', realName: 'email' },
            { name: 'setpassword', realName: 'setpassword' },
            { name: 'password', realName: 'password' },
            { name: 'creditType', realName: 'credit_type' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Createsubaccount;
