
/**
 * PepipostAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Emailv1
 *
 * @constructor
 */
Emailv1 = function (obj) {
    if(!obj) {
        this.apiKey = null;     
        this.attributes = null;     
        this.emailDetails = null;     
        this.files = null;     
        this.recipients = null;     
        this.settings = null;     
        this.xAPIHEADER = null;     
        //Append to variable dictionary
        this._variableDict['apiKey'] = 'api_key';
        this._variableDict['emailDetails'] = 'email_details';
        this._variableDict['xAPIHEADER'] = 'X-APIHEADER';
    } else {
        this.apiKey = obj.api_key;
        this.attributes = new Attributes(obj.attributes);
        this.emailDetails = new EmailDetails(obj.email_details);
        this.files = new Files(obj.files);
        this.recipients = obj.recipients;
        this.settings = new Settings(obj.settings);
        this.xAPIHEADER = obj.X-APIHEADER;
        //Append to variable dictionary
        this._variableDict['apiKey'] = 'api_key';
        this._variableDict['emailDetails'] = 'email_details';
        this._variableDict['xAPIHEADER'] = 'X-APIHEADER';
    }
};

Emailv1.prototype = new BaseModel();
Emailv1.prototype.constructor = Emailv1;

/**
 * Your secret API Key
 *
 * @return {string|null}
 */
Emailv1.prototype.getApiKey = function() {
    return this.apiKey;
};

/**
 * Setter for ApiKey
 * 
 * @param {string|null} value 
 */
Emailv1.prototype.setApiKey = function(value) {
    this.apiKey = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Attributes|null}
 */
Emailv1.prototype.getAttributes = function() {
    return this.attributes;
};

/**
 * Setter for Attributes
 * 
 * @param {Attributes|null} value 
 */
Emailv1.prototype.setAttributes = function(value) {
    this.attributes = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {EmailDetails|null}
 */
Emailv1.prototype.getEmailDetails = function() {
    return this.emailDetails;
};

/**
 * Setter for EmailDetails
 * 
 * @param {EmailDetails|null} value 
 */
Emailv1.prototype.setEmailDetails = function(value) {
    this.emailDetails = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Files|null}
 */
Emailv1.prototype.getFiles = function() {
    return this.files;
};

/**
 * Setter for Files
 * 
 * @param {Files|null} value 
 */
Emailv1.prototype.setFiles = function(value) {
    this.files = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array|null}
 */
Emailv1.prototype.getRecipients = function() {
    return this.recipients;
};

/**
 * Setter for Recipients
 * 
 * @param {array|null} value 
 */
Emailv1.prototype.setRecipients = function(value) {
    this.recipients = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Settings|null}
 */
Emailv1.prototype.getSettings = function() {
    return this.settings;
};

/**
 * Setter for Settings
 * 
 * @param {Settings|null} value 
 */
Emailv1.prototype.setSettings = function(value) {
    this.settings = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array|null}
 */
Emailv1.prototype.getXAPIHEADER = function() {
    return this.xAPIHEADER;
};

/**
 * Setter for XAPIHEADER
 * 
 * @param {array|null} value 
 */
Emailv1.prototype.setXAPIHEADER = function(value) {
    this.xAPIHEADER = value;
};


module.exports = Emailv1;