
/**
 * PepipostAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of EmailDetails
 *
 * @constructor
 */
EmailDetails = function (obj) {
    if(!obj) {
        this.content = null;     
        this.from = null;     
        this.fromname = null;     
        this.replytoid = null;     
        this.subject = null;     
        this.tags = null;     
    } else {
        this.content = obj.content;
        this.from = obj.from;
        this.fromname = obj.fromname;
        this.replytoid = obj.replytoid;
        this.subject = obj.subject;
        this.tags = obj.tags;
    }
};

EmailDetails.prototype = new BaseModel();
EmailDetails.prototype.constructor = EmailDetails;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
EmailDetails.prototype.getContent = function() {
    return this.content;
};

/**
 * Setter for Content
 * 
 * @param {string|null} value 
 */
EmailDetails.prototype.setContent = function(value) {
    this.content = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
EmailDetails.prototype.getFrom = function() {
    return this.from;
};

/**
 * Setter for From
 * 
 * @param {string|null} value 
 */
EmailDetails.prototype.setFrom = function(value) {
    this.from = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
EmailDetails.prototype.getFromname = function() {
    return this.fromname;
};

/**
 * Setter for Fromname
 * 
 * @param {string|null} value 
 */
EmailDetails.prototype.setFromname = function(value) {
    this.fromname = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
EmailDetails.prototype.getReplytoid = function() {
    return this.replytoid;
};

/**
 * Setter for Replytoid
 * 
 * @param {string|null} value 
 */
EmailDetails.prototype.setReplytoid = function(value) {
    this.replytoid = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
EmailDetails.prototype.getSubject = function() {
    return this.subject;
};

/**
 * Setter for Subject
 * 
 * @param {string|null} value 
 */
EmailDetails.prototype.setSubject = function(value) {
    this.subject = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
EmailDetails.prototype.getTags = function() {
    return this.tags;
};

/**
 * Setter for Tags
 * 
 * @param {string|null} value 
 */
EmailDetails.prototype.setTags = function(value) {
    this.tags = value;
};


module.exports = EmailDetails;