/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EmailBody
 */
class EmailBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.personalizations = this.constructor.getValue(obj.personalizations);
        this.tags = this.constructor.getValue(obj.tags);
        this.from = this.constructor.getValue(obj.from);
        this.subject = this.constructor.getValue(obj.subject);
        this.content = this.constructor.getValue(obj.content);
        this.ampcontent = this.constructor.getValue(obj.ampcontent);
        this.attachments = this.constructor.getValue(obj.attachments);
        this.settings = this.constructor.getValue(obj.settings);
        this.replyToId = this.constructor.getValue(obj.replyToId);
        this.templateId = this.constructor.getValue(obj.templateId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'personalizations',
                realName: 'personalizations',
                array: true,
                type: 'Personalizations',
            },
            { name: 'tags', realName: 'tags' },
            { name: 'from', realName: 'from', type: 'From' },
            { name: 'subject', realName: 'subject' },
            { name: 'content', realName: 'content' },
            { name: 'ampcontent', realName: 'ampcontent' },
            {
                name: 'attachments',
                realName: 'attachments',
                array: true,
                type: 'EmailBodyAttachments',
            },
            { name: 'settings', realName: 'settings', type: 'Settings' },
            { name: 'replyToId', realName: 'replyToId' },
            { name: 'templateId', realName: 'templateId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EmailBody;
