/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const EventsEnum = {

    /**
     * TODO: Write general description for this element
     */
    PROCESSED: 'processed',

    /**
     * TODO: Write general description for this element
     */
    SENT: 'sent',

    /**
     * TODO: Write general description for this element
     */
    OPEN: 'open',

    /**
     * TODO: Write general description for this element
     */
    CLICK: 'click',

    /**
     * TODO: Write general description for this element
     */
    UNSUBSCRIBE: 'unsubscribe',

    /**
     * TODO: Write general description for this element
     */
    BOUNCE: 'bounce',

    /**
     * TODO: Write general description for this element
     */
    SOFTBOUNCE: 'softbounce',

    /**
     * TODO: Write general description for this element
     */
    SPAM: 'spam',

    /**
     * TODO: Write general description for this element
     */
    INVALID: 'invalid',

    /**
     * TODO: Write general description for this element
     */
    DROPPED: 'dropped',

    /**
     * TODO: Write general description for this element
     */
    HARDBOUNCE: 'hardbounce',

};

module.exports = EventsEnum;
