
/**
 * PepipostAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/20/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Files
 *
 * @constructor
 */
Files = function (obj) {
    if(!obj) {
        this.exampleAttachment1Txt = null;     
        //Append to variable dictionary
        this._variableDict['exampleAttachment1Txt'] = 'example_attachment1.txt';
    } else {
        this.exampleAttachment1Txt = obj.example_attachment1.txt;
        //Append to variable dictionary
        this._variableDict['exampleAttachment1Txt'] = 'example_attachment1.txt';
    }
};

Files.prototype = new BaseModel();
Files.prototype.constructor = Files;

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Files.prototype.getExampleAttachment1Txt = function() {
    return this.exampleAttachment1Txt;
};

/**
 * Setter for ExampleAttachment1Txt
 * 
 * @param {string|null} value 
 */
Files.prototype.setExampleAttachment1Txt = function(value) {
    this.exampleAttachment1Txt = value;
};


module.exports = Files;