/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SortEnum = {

    /**
     * TODO: Write general description for this element
     */
    ASC: 'asc',

    /**
     * TODO: Write general description for this element
     */
    DESC: 'desc',

};

module.exports = SortEnum;
