/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TimeperiodEnum = {

    /**
     * TODO: Write general description for this element
     */
    DAILY: 'daily',

    /**
     * TODO: Write general description for this element
     */
    WEEKLY: 'weekly',

    /**
     * TODO: Write general description for this element
     */
    MONHTLY: 'monhtly',

};

module.exports = TimeperiodEnum;
