/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    AMP: 'amp',

    /**
     * TODO: Write general description for this element
     */
    HTML: 'html',

};

module.exports = TypeEnum;
