/**
 * PepipostAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/20/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://api.pepipost.com"

};

module.exports = configuration;

