/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'https://api.pepipost.com/v5.1',

    // Your Pepipost API Key. You will find the api key in the Pepipost application in Integrations.
    apiKey: '',

};

module.exports = Configuration;
