/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Attribute = require('../lib/Models/Attribute');
const From = require('../lib/Models/From');
const Xheaders = require('../lib/Models/Xheaders');
const EmailBodyAttachments = require('../lib/Models/EmailBodyAttachments');
const Attachments = require('../lib/Models/Attachments');
const Personalizations = require('../lib/Models/Personalizations');
const EmailBody = require('../lib/Models/EmailBody');
const Settings = require('../lib/Models/Settings');
const SendEmailError = require('../lib/Models/SendEmailError');
const SendEmailResponse = require('../lib/Models/SendEmailResponse');

const classMap = {
    Attribute,
    Xheaders,
    From,
    EmailBodyAttachments,
    Attachments,
    Personalizations,
    EmailBody,
    Settings,
    SendEmailError,
    SendEmailResponse,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
