/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Content = require('../lib/Models/Content');
const Personalizations = require('../lib/Models/Personalizations');
const From = require('../lib/Models/From');
const Settings = require('../lib/Models/Settings');
const EmailStruct = require('../lib/Models/EmailStruct');
const Attachments = require('../lib/Models/Attachments');
const Send = require('../lib/Models/Send');
const DomainStruct = require('../lib/Models/DomainStruct');
const Deletedomain = require('../lib/Models/Deletedomain');
const AddemailordomaintoSuppressionlist =
  require('../lib/Models/AddemailordomaintoSuppressionlist');
const RemoveemailordomaintoSuppressionlist =
  require('../lib/Models/RemoveemailordomaintoSuppressionlist');
const Createsubaccount = require('../lib/Models/Createsubaccount');
const Updatesubaccount = require('../lib/Models/Updatesubaccount');
const UpdateCredisofsubaccount = require('../lib/Models/UpdateCredisofsubaccount');
const UpdaterecurringCredisofsubaccount =
  require('../lib/Models/UpdaterecurringCredisofsubaccount');
const Deletesubacoount = require('../lib/Models/Deletesubacoount');
const Enableordisablesubacoount = require('../lib/Models/Enableordisablesubacoount');

const classMap = {
    Content,
    Personalizations,
    From,
    Settings,
    EmailStruct,
    Attachments,
    Send,
    DomainStruct,
    Deletedomain,
    AddemailordomaintoSuppressionlist,
    RemoveemailordomaintoSuppressionlist,
    Createsubaccount,
    Updatesubaccount,
    UpdateCredisofsubaccount,
    UpdaterecurringCredisofsubaccount,
    Deletesubacoount,
    Enableordisablesubacoount,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
