/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const From = require('../lib/Models/From');
const Settings = require('../lib/Models/Settings');
const Content = require('../lib/Models/Content');
const Attachments = require('../lib/Models/Attachments');
const EmailStruct = require('../lib/Models/EmailStruct');
const Personalizations = require('../lib/Models/Personalizations');
const Send = require('../lib/Models/Send');

const classMap = {
    From,
    Settings,
    Content,
    Attachments,
    EmailStruct,
    Personalizations,
    Send,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
