/**
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    SERVER_1: 'server1',

};

module.exports = Servers;
